/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const ProductsIndexLazyImport = createFileRoute('/products/')()
const OwnerIndexLazyImport = createFileRoute('/owner/')()
const EmployeeIndexLazyImport = createFileRoute('/employee/')()
const IndexLazyImport = createFileRoute('//')()
const ProductsProductTypeLazyImport = createFileRoute(
  '/products/$productType',
)()
const OwnerPromotionsLazyImport = createFileRoute('/owner/promotions')()
const OwnerProductsLazyImport = createFileRoute('/owner/products')()
const OwnerOrdersLazyImport = createFileRoute('/owner/orders')()
const OwnerEmployeesLazyImport = createFileRoute('/owner/employees')()
const OwnerDashboardLazyImport = createFileRoute('/owner/dashboard')()
const EmployeeProductsLazyImport = createFileRoute('/employee/products')()
const EmployeeOrdersLazyImport = createFileRoute('/employee/orders')()
const EmployeeEmployeesLazyImport = createFileRoute('/employee/employees')()
const TrackingLazyImport = createFileRoute('//tracking')()
const SignupLazyImport = createFileRoute('//signup')()
const RecruitmentLazyImport = createFileRoute('//recruitment')()
const ProductsLazyImport = createFileRoute('//products')()
const CartLazyImport = createFileRoute('//cart')()
const AccountLazyImport = createFileRoute('//account')()
const AboutLazyImport = createFileRoute('//about')()

// Create/Update Routes

const ProductsIndexLazyRoute = ProductsIndexLazyImport.update({
  path: '/products/',
  getParentRoute: () => rootRoute,
}).lazy(() => import('./routes/products/index.lazy').then((d) => d.Route))

const OwnerIndexLazyRoute = OwnerIndexLazyImport.update({
  path: '/owner/',
  getParentRoute: () => rootRoute,
}).lazy(() => import('./routes/owner/index.lazy').then((d) => d.Route))

const EmployeeIndexLazyRoute = EmployeeIndexLazyImport.update({
  path: '/employee/',
  getParentRoute: () => rootRoute,
}).lazy(() => import('./routes/employee/index.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
}).lazy(() => import('./routes/_/index.lazy').then((d) => d.Route))

const ProductsProductTypeLazyRoute = ProductsProductTypeLazyImport.update({
  path: '/products/$productType',
  getParentRoute: () => rootRoute,
}).lazy(() =>
  import('./routes/products/$productType.lazy').then((d) => d.Route),
)

const OwnerPromotionsLazyRoute = OwnerPromotionsLazyImport.update({
  path: '/owner/promotions',
  getParentRoute: () => rootRoute,
}).lazy(() => import('./routes/owner/promotions.lazy').then((d) => d.Route))

const OwnerProductsLazyRoute = OwnerProductsLazyImport.update({
  path: '/owner/products',
  getParentRoute: () => rootRoute,
}).lazy(() => import('./routes/owner/products.lazy').then((d) => d.Route))

const OwnerOrdersLazyRoute = OwnerOrdersLazyImport.update({
  path: '/owner/orders',
  getParentRoute: () => rootRoute,
}).lazy(() => import('./routes/owner/orders.lazy').then((d) => d.Route))

const OwnerEmployeesLazyRoute = OwnerEmployeesLazyImport.update({
  path: '/owner/employees',
  getParentRoute: () => rootRoute,
}).lazy(() => import('./routes/owner/employees.lazy').then((d) => d.Route))

const OwnerDashboardLazyRoute = OwnerDashboardLazyImport.update({
  path: '/owner/dashboard',
  getParentRoute: () => rootRoute,
}).lazy(() => import('./routes/owner/dashboard.lazy').then((d) => d.Route))

const EmployeeProductsLazyRoute = EmployeeProductsLazyImport.update({
  path: '/employee/products',
  getParentRoute: () => rootRoute,
}).lazy(() => import('./routes/employee/products.lazy').then((d) => d.Route))

const EmployeeOrdersLazyRoute = EmployeeOrdersLazyImport.update({
  path: '/employee/orders',
  getParentRoute: () => rootRoute,
}).lazy(() => import('./routes/employee/orders.lazy').then((d) => d.Route))

const EmployeeEmployeesLazyRoute = EmployeeEmployeesLazyImport.update({
  path: '/employee/employees',
  getParentRoute: () => rootRoute,
}).lazy(() => import('./routes/employee/employees.lazy').then((d) => d.Route))

const TrackingLazyRoute = TrackingLazyImport.update({
  path: '/tracking',
  getParentRoute: () => rootRoute,
}).lazy(() => import('./routes/_/tracking.lazy').then((d) => d.Route))

const SignupLazyRoute = SignupLazyImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
}).lazy(() => import('./routes/_/signup.lazy').then((d) => d.Route))

const RecruitmentLazyRoute = RecruitmentLazyImport.update({
  path: '/recruitment',
  getParentRoute: () => rootRoute,
}).lazy(() => import('./routes/_/recruitment.lazy').then((d) => d.Route))

const ProductsLazyRoute = ProductsLazyImport.update({
  path: '/products',
  getParentRoute: () => rootRoute,
}).lazy(() => import('./routes/_/products.lazy').then((d) => d.Route))

const CartLazyRoute = CartLazyImport.update({
  path: '/cart',
  getParentRoute: () => rootRoute,
}).lazy(() => import('./routes/_/cart.lazy').then((d) => d.Route))

const AccountLazyRoute = AccountLazyImport.update({
  path: '/account',
  getParentRoute: () => rootRoute,
}).lazy(() => import('./routes/_/account.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
}).lazy(() => import('./routes/_/about.lazy').then((d) => d.Route))

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  AboutLazyRoute,
  AccountLazyRoute,
  CartLazyRoute,
  ProductsLazyRoute,
  RecruitmentLazyRoute,
  SignupLazyRoute,
  TrackingLazyRoute,
  EmployeeEmployeesLazyRoute,
  EmployeeOrdersLazyRoute,
  EmployeeProductsLazyRoute,
  OwnerDashboardLazyRoute,
  OwnerEmployeesLazyRoute,
  OwnerOrdersLazyRoute,
  OwnerProductsLazyRoute,
  OwnerPromotionsLazyRoute,
  ProductsProductTypeLazyRoute,
  IndexLazyRoute,
  EmployeeIndexLazyRoute,
  OwnerIndexLazyRoute,
  ProductsIndexLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "//about",
        "//account",
        "//cart",
        "//products",
        "//recruitment",
        "//signup",
        "//tracking",
        "/employee/employees",
        "/employee/orders",
        "/employee/products",
        "/owner/dashboard",
        "/owner/employees",
        "/owner/orders",
        "/owner/products",
        "/owner/promotions",
        "/products/$productType",
        "//",
        "/employee/",
        "/owner/",
        "/products/"
      ]
    },
    "//about": {
      "filePath": "_/about.lazy.jsx"
    },
    "//account": {
      "filePath": "_/account.lazy.jsx"
    },
    "//cart": {
      "filePath": "_/cart.lazy.jsx"
    },
    "//products": {
      "filePath": "_/products.lazy.jsx"
    },
    "//recruitment": {
      "filePath": "_/recruitment.lazy.jsx"
    },
    "//signup": {
      "filePath": "_/signup.lazy.jsx"
    },
    "//tracking": {
      "filePath": "_/tracking.lazy.jsx"
    },
    "/employee/employees": {
      "filePath": "employee/employees.lazy.jsx"
    },
    "/employee/orders": {
      "filePath": "employee/orders.lazy.jsx"
    },
    "/employee/products": {
      "filePath": "employee/products.lazy.jsx"
    },
    "/owner/dashboard": {
      "filePath": "owner/dashboard.lazy.jsx"
    },
    "/owner/employees": {
      "filePath": "owner/employees.lazy.jsx"
    },
    "/owner/orders": {
      "filePath": "owner/orders.lazy.jsx"
    },
    "/owner/products": {
      "filePath": "owner/products.lazy.jsx"
    },
    "/owner/promotions": {
      "filePath": "owner/promotions.lazy.jsx"
    },
    "/products/$productType": {
      "filePath": "products/$productType.lazy.jsx"
    },
    "//": {
      "filePath": "_/index.lazy.jsx"
    },
    "/employee/": {
      "filePath": "employee/index.lazy.jsx"
    },
    "/owner/": {
      "filePath": "owner/index.lazy.jsx"
    },
    "/products/": {
      "filePath": "products/index.lazy.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
